import React, { useEffect, useMemo, useState } from 'react';
import { database } from '../../shared/utils/electron-api';

type PrintRow = {
  name: string;
  id_number?: string;
  phone?: string;
  email?: string;
  address?: string;
  status?: string;
  time?: string;
};

type SettingsMap = Record<string, any>;

const getElectronAPI = (): any | null => {
  try {
    const w = window as any;
    if (w && w.electronAPI) return w.electronAPI;
    return null;
  } catch {
    return null;
  }
};

function getDateFromHash(): string {
  const hash = window.location.hash || '';
  const match = hash.match(/date=([0-9\-]+)/);
  if (match && match[1]) return match[1];
  return new Date().toISOString().split('T')[0];
}

const formatDisplayDate = (iso: string) => {
  const d = new Date(`${iso}T00:00:00`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
};

const fallbackSettings = (): SettingsMap => ({
  'org.name': '',
  'org.address': '',
  'org.phone': '',
  'org.email': '',
  'org.logo_path': '',
  'org.stamp_path': '',

  'locale.ui_language': 'en',
  'print.privacy_level': 'internal',
  'print.disclaimer.enabled': false,
  'print.disclaimer.text': {
    en: '',
    fr: '',
    ar: '',
  },

  'print.fields': {
    full_name: true,
    id_number: true,
    phone: false,
    email: false,
    address: false,
    status: true,
    time: true,
    signature: false,
  },
});

/**
 * Senior-grade print layout:
 * - Screen: A4 width, natural scroll, no clipping.
 * - Print: clean output, toolbar hidden, browser paginates.
 * - No vh constraints.
 */
const DocumentLayout: React.FC<{
  title?: string;
  settings: SettingsMap;
  children: React.ReactNode;
}> = ({ title, settings, children }) => {
  const orgName = settings['org.name'] || '';
  const orgAddress = settings['org.address'] || '';
  const orgPhone = settings['org.phone'] || '';
  const orgEmail = settings['org.email'] || '';
  const logoPath = settings['org.logo_path'] || '';
  const stampPath = settings['org.stamp_path'] || '';

  const privacyLevel = settings['print.privacy_level'] || 'internal';
  const disclaimerEnabled = settings['print.disclaimer.enabled'] === true;

  const uiLang = settings['locale.ui_language'] || 'en';
  const disclaimerText =
    settings?.['print.disclaimer.text']?.[uiLang] ||
    settings?.['print.disclaimer.text']?.en ||
    '';

  const issuedAt = new Date().toLocaleString();

  const isRTL = uiLang === 'ar';

  return (
    <div className="ap-doc" dir={isRTL ? 'rtl' : 'ltr'}>
      {/* HEADER */}
      <header className="ap-header">
        <div className="ap-org">
          {logoPath ? (
            <img
              src={`file://${logoPath}`}
              alt="Organization Logo"
              className="ap-logo"
            />
          ) : null}

          <div className="ap-org-name">{orgName || ' '}</div>

          {orgAddress ? <div className="ap-org-line">{orgAddress}</div> : null}
          {orgPhone ? <div className="ap-org-line">Tel: {orgPhone}</div> : null}
          {orgEmail ? <div className="ap-org-line">Email: {orgEmail}</div> : null}
        </div>

        <div className="ap-meta">
          {title ? <div className="ap-title">{title}</div> : null}
          <div className="ap-meta-line">Privacy level: {privacyLevel}</div>
          <div className="ap-meta-line">Issued on: {issuedAt}</div>
        </div>
      </header>

      {/* BODY */}
      <main className="ap-body">{children}</main>

      {/* FOOTER */}
      <footer className="ap-footer">
        <div className="ap-footer-left">
          {disclaimerEnabled && disclaimerText ? (
            <div className="ap-disclaimer">{disclaimerText}</div>
          ) : null}
          <div>Generated by AttendancePro</div>
        </div>

        {stampPath ? (
          <img
            src={`file://${stampPath}`}
            alt="Electronic Stamp"
            className="ap-stamp"
          />
        ) : null}
      </footer>
    </div>
  );
};

const AttendancePrintReport: React.FC = () => {
  const [date] = useState<string>(getDateFromHash());
  const [rows, setRows] = useState<PrintRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [printing, setPrinting] = useState(false);

  const [settings, setSettings] = useState<SettingsMap | null>(null);

  const electronAPI = useMemo(() => getElectronAPI(), []);

  /* ================= LOAD SETTINGS ================= */
  useEffect(() => {
    let mounted = true;

    const loadSettings = async () => {
      const api = electronAPI;

      try {
        if (!api || !api.settings || typeof api.settings.getAll !== 'function') {
          if (!mounted) return;
          setSettings(fallbackSettings());
          return;
        }

        const res = await api.settings.getAll();
        if (!mounted) return;
        setSettings(res?.success && res.data ? res.data : fallbackSettings());
      } catch {
        if (!mounted) return;
        setSettings(fallbackSettings());
      }
    };

    loadSettings();
    return () => {
      mounted = false;
    };
  }, [electronAPI]);

  /* ================= LOAD ATTENDANCE ================= */
  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      try {
        const result = await database.query(
          `
          SELECT
            s.name,
            s.id_number,
            s.phone,
            s.email,
            s.address,
            a.status,
            a.created_at AS time
          FROM attendance a
          JOIN subscribers s ON s.id = a.subscriber_id
          WHERE DATE(a.date) = :date
          ORDER BY s.name ASC
          `,
          { date }
        );

        const data =
          Array.isArray(result?.data)
            ? result.data
            : Array.isArray(result?.rows)
              ? result.rows
              : Array.isArray(result)
                ? result
                : [];

        if (!cancelled) setRows(data);
      } catch {
        if (!cancelled) setRows([]);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [date]);

  const handlePrint = () => {
    if (printing) return;
    setPrinting(true);
    setTimeout(() => {
      try {
        window.print();
      } finally {
        setTimeout(() => setPrinting(false), 1200);
      }
    }, 50);
  };

  const handleClose = () => {
    if (printing) return;
    window.close();
  };

  if (!settings) {
    return <div className="p-6 text-sm text-gray-500">Preparing document…</div>;
  }

  const fields = settings['print.fields'] || {};
  const enabledColsCount =
    Object.values(fields).filter(Boolean).length > 0
      ? Object.values(fields).filter(Boolean).length
      : 1;

  const title = `Attendance — ${formatDisplayDate(date)}`;

  return (
    <div className="ap-shell">
      {/* TOOLBAR (never prints) */}
      <div className="ap-toolbar no-print">
        <div className="ap-toolbar-title">{title}</div>

        <div className="ap-toolbar-actions">
          <button
            onClick={handlePrint}
            disabled={printing || loading}
            className="ap-btn ap-btn-primary"
          >
            {printing ? 'Preparing…' : 'Print'}
          </button>

          <button
            onClick={handleClose}
            disabled={printing}
            className="ap-btn ap-btn-secondary"
          >
            Close
          </button>
        </div>
      </div>

      {/* DOCUMENT (scrolls naturally on screen, browser paginates on print) */}
      <div className="ap-preview">
        <DocumentLayout title={title} settings={settings}>
          <table className="ap-table">
            <thead>
              <tr>
                {fields.full_name && <th>Full Name</th>}
                {fields.id_number && <th>ID Number</th>}
                {fields.phone && <th>Phone</th>}
                {fields.email && <th>Email</th>}
                {fields.address && <th>Address</th>}
                {fields.status && <th>Status</th>}
                {fields.time && <th>Time</th>}
                {fields.signature && <th>Signature</th>}
              </tr>
            </thead>

            <tbody>
              {rows.map((r, i) => (
                <tr key={i}>
                  {fields.full_name && <td>{r.name}</td>}
                  {fields.id_number && <td>{r.id_number || ''}</td>}
                  {fields.phone && <td>{r.phone || ''}</td>}
                  {fields.email && <td>{r.email || ''}</td>}
                  {fields.address && <td>{r.address || ''}</td>}
                  {fields.status && <td>{r.status || ''}</td>}
                  {fields.time && (
                    <td>{r.time ? new Date(r.time).toLocaleTimeString() : ''}</td>
                  )}
                  {fields.signature && <td />}
                </tr>
              ))}

              {!loading && rows.length === 0 && (
                <tr>
                  <td colSpan={enabledColsCount} className="ap-empty">
                    No attendance records for this date.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </DocumentLayout>
      </div>

      <style>
        {`
          /* ===== Screen: professional document viewer ===== */
          @media screen {
            html, body, #root {
              height: 100%;
              overflow: auto;
            }

            .ap-shell {
              background: #f1f5f9;
              min-height: 100%;
            }

            .ap-toolbar {
              position: sticky;
              top: 0;
              z-index: 1000;
              background: #ffffff;
              border-bottom: 1px solid #cbd5e1;
              padding: 10px 16px;
              display: flex;
              justify-content: space-between;
              align-items: center;
              gap: 12px;
            }

            .ap-toolbar-title {
              font-weight: 700;
              white-space: nowrap;
              overflow: hidden;
              text-overflow: ellipsis;
              max-width: 70%;
            }

            .ap-toolbar-actions {
              display: flex;
              gap: 8px;
              align-items: center;
              flex-shrink: 0;
            }

            .ap-btn {
              padding: 6px 12px;
              border-radius: 6px;
              border: 1px solid transparent;
              cursor: pointer;
              font-size: 13px;
              line-height: 1.2;
            }

            .ap-btn:disabled {
              opacity: 0.6;
              cursor: not-allowed;
            }

            .ap-btn-primary {
              background: #2563eb;
              color: #fff;
            }

            .ap-btn-secondary {
              background: #f3f4f6;
              border-color: #9ca3af;
              color: #111827;
            }

            /* Center the A4 canvas and allow full vertical scroll */
            .ap-preview {
              padding: 18px 0 28px 0;
              display: flex;
              justify-content: center;
            }

            .ap-doc {
              width: 210mm;           /* A4 width */
              background: #ffffff;
              color: #000000;
              font-family: Arial, Helvetica, sans-serif;
              padding: 40px;
              box-shadow: 0 0 10px rgba(0,0,0,0.25);
              /* CRITICAL: no vh constraints, no overflow clipping */
              overflow: visible;
            }

            .ap-header {
              display: flex;
              justify-content: space-between;
              align-items: flex-start;
              gap: 24px;
              border-bottom: 2px solid #000;
              padding-bottom: 12px;
              margin-bottom: 24px;
            }

            .ap-org { max-width: 70%; }
            .ap-logo { height: 70px; object-fit: contain; margin-bottom: 8px; }
            .ap-org-name { font-size: 18px; font-weight: 700; }
            .ap-org-line { font-size: 12px; }

            .ap-meta { text-align: right; min-width: 240px; }
            .ap-title { font-size: 20px; font-weight: 800; }
            .ap-meta-line { font-size: 11px; margin-top: 6px; }

            .ap-body { }

            .ap-footer {
              border-top: 1px solid #000;
              margin-top: 30px;
              padding-top: 12px;
              display: flex;
              justify-content: space-between;
              align-items: flex-end;
              gap: 24px;
              font-size: 11px;
            }

            .ap-footer-left { max-width: 70%; }
            .ap-disclaimer { margin-bottom: 8px; }
            .ap-stamp { height: 90px; object-fit: contain; opacity: 0.9; }

            /* Table: ministry/bank-grade */
            .ap-table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 18px;
              table-layout: fixed;
            }

            .ap-table th,
            .ap-table td {
              border: 1px solid #000;
              padding: 8px;
              font-size: 12px;
              vertical-align: top;
              word-break: break-word;
            }

            .ap-table th {
              font-weight: 700;
              text-align: center;
            }

            .ap-empty {
              text-align: center;
              padding: 14px;
              font-weight: 600;
            }
          }

          /* ===== Print: clean output, browser paginates ===== */
          @media print {
            .no-print { display: none !important; }

            html, body {
              background: #ffffff !important;
            }

            .ap-shell {
              background: #ffffff !important;
            }

            .ap-preview {
              padding: 0 !important;
              display: block !important;
            }

            .ap-doc {
              width: auto !important;
              box-shadow: none !important;
              padding: 40px !important;
            }

            /* Improve multi-page table printing */
            thead { display: table-header-group; }
            tfoot { display: table-footer-group; }
            tr { page-break-inside: avoid; }
          }
        `}
      </style>
    </div>
  );
};

export default AttendancePrintReport;
