import React, { useEffect, useState } from 'react';

type SettingsMap = Record<string, any>;

type PrintLayoutProps = {
  title?: string;
  children: React.ReactNode;
};

const PrintLayout: React.FC<PrintLayoutProps> = ({ title, children }) => {
  const [settings, setSettings] = useState<SettingsMap | null>(null);

  useEffect(() => {
    let mounted = true;

    window.electronAPI.settings
      .getAll()
      .then((res: any) => {
        if (!mounted) return;
        if (res?.success && res.data) {
          setSettings(res.data);
        }
      })
      .catch(() => {
        // Printing must never crash
      });

    return () => {
      mounted = false;
    };
  }, []);

  if (!settings) {
    return <div className="p-6 text-sm text-gray-500">Preparing document…</div>;
  }

  /* ================= SETTINGS ================= */

  const orgName = settings['org.name'] || '';
  const orgAddress = settings['org.address'] || '';
  const orgPhone = settings['org.phone'] || '';
  const orgEmail = settings['org.email'] || '';
  const logoPath = settings['org.logo_path'] || '';
  const stampPath = settings['org.stamp_path'] || '';

  const privacyLevel = settings['print.privacy_level'] || 'internal';
  const disclaimerEnabled = settings['print.disclaimer.enabled'] !== false;

  const uiLang = settings['locale.ui_language'] || 'en';
  const disclaimerText =
    settings['print.disclaimer.text']?.[uiLang] ||
    settings['print.disclaimer.text']?.en ||
    '';

  const issuedAt = new Date().toLocaleString();

  /* ================= RENDER ================= */

  return (
    <div className="print-screen-root">
      {/* Screen-only page canvas */}
      <div className="print-screen-page">
        {/* ================= HEADER ================= */}
        <header
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            borderBottom: '2px solid #000',
            paddingBottom: '12px',
            marginBottom: '24px',
          }}
        >
          <div style={{ maxWidth: '70%' }}>
            {logoPath && (
              <img
                src={`file://${logoPath}`}
                alt="Organization Logo"
                style={{ height: '70px', objectFit: 'contain', marginBottom: '8px' }}
              />
            )}

            <div style={{ fontSize: '18px', fontWeight: 'bold' }}>
              {orgName}
            </div>

            {orgAddress && <div style={{ fontSize: '12px' }}>{orgAddress}</div>}
            {orgPhone && <div style={{ fontSize: '12px' }}>Tel: {orgPhone}</div>}
            {orgEmail && <div style={{ fontSize: '12px' }}>Email: {orgEmail}</div>}
          </div>

          <div style={{ textAlign: 'right' }}>
            {title && (
              <div style={{ fontSize: '20px', fontWeight: 'bold' }}>{title}</div>
            )}
            <div style={{ fontSize: '11px', marginTop: '6px' }}>
              Privacy level: {privacyLevel}
            </div>
          </div>
        </header>

        {/* ================= BODY ================= */}
        <main>{children}</main>

        {/* ================= FOOTER ================= */}
        <footer
          style={{
            borderTop: '1px solid #000',
            marginTop: '30px',
            paddingTop: '12px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'flex-end',
            fontSize: '11px',
          }}
        >
          <div style={{ maxWidth: '70%' }}>
            {disclaimerEnabled && disclaimerText && (
              <div style={{ marginBottom: '8px' }}>{disclaimerText}</div>
            )}
            <div>Issued on: {issuedAt}</div>
            <div>Generated by AttendancePro</div>
          </div>

          {stampPath && (
            <img
              src={`file://${stampPath}`}
              alt="Electronic Stamp"
              style={{ height: '90px', objectFit: 'contain', opacity: 0.9 }}
            />
          )}
        </footer>
      </div>

      {/* ================= STYLE RULES ================= */}
      <style>
        {`
          /* ===== Screen Preview ===== */
          @media screen {
            body {
              background: #e5e7eb;
            }

            .print-screen-root {
              padding: 24px;
            }

            .print-screen-page {
              background: #ffffff;
              color: #000000;
              font-family: Arial, Helvetica, sans-serif;
              padding: 40px;
              margin: 0 auto 24px auto;
              width: 210mm;
              min-height: 297mm;
              box-shadow: 0 0 10px rgba(0,0,0,0.25);
            }
          }

          /* ===== Print Output ===== */
          @media print {
            body {
              background: #ffffff;
            }

            .print-screen-root {
              padding: 0;
            }

            .print-screen-page {
              width: auto;
              min-height: auto;
              margin: 0;
              padding: 40px;
              box-shadow: none;
            }
          }
        `}
      </style>
    </div>
  );
};

export default PrintLayout;
